### ISSUE TITLE
Open External Anchors Using rel="noopener"

### ISSUE THREAD

**Issue by bernhard-hofmann** [Freegle/iznik#2]
Opening in target="_blank" is a security vulnerability since the new page has access to our window object via window.opener, and it can navigate our page to a different URL using window.opener.location = newURL.

https://developers.google.com/web/tools/lighthouse/audits/noopener

**Comment by chriscant** [comment]
It's pretty poor that browsers allow this - and it sounds like they are being fixed up...

**Comment by bernhard-hofmann** [comment]
Edward will hopefully merge the fixes in the "noopener" branch I pushed earlier. ☺
